package com.projectronin.interop.fhir.ronin.generators.resource.observation

import com.projectronin.interop.fhir.generators.datatypes.codeableConcept
import com.projectronin.interop.fhir.generators.datatypes.coding
import com.projectronin.interop.fhir.generators.resources.ObservationGenerator
import com.projectronin.interop.fhir.generators.resources.observation
import com.projectronin.interop.fhir.r4.CodeSystem
import com.projectronin.interop.fhir.r4.datatype.CodeableConcept
import com.projectronin.interop.fhir.r4.datatype.Coding
import com.projectronin.interop.fhir.r4.datatype.DynamicValue
import com.projectronin.interop.fhir.r4.datatype.DynamicValueType
import com.projectronin.interop.fhir.r4.datatype.Quantity
import com.projectronin.interop.fhir.r4.datatype.primitive.Code
import com.projectronin.interop.fhir.r4.datatype.primitive.Decimal
import com.projectronin.interop.fhir.r4.datatype.primitive.asFHIR
import com.projectronin.interop.fhir.r4.resource.Observation
import com.projectronin.interop.fhir.r4.resource.ObservationComponent
import com.projectronin.interop.fhir.ronin.generators.util.generateCodeableConcept
import com.projectronin.interop.fhir.ronin.generators.util.generateEffectiveDateTime
import com.projectronin.interop.fhir.ronin.generators.util.generateExtension
import com.projectronin.interop.fhir.ronin.generators.util.generateSubject
import com.projectronin.interop.fhir.ronin.generators.util.rcdmIdentifiers
import com.projectronin.interop.fhir.ronin.generators.util.rcdmMeta
import com.projectronin.interop.fhir.ronin.profile.RoninProfile

/**
 * Helps generate ronin pulse oximetry observation profile, applies meta and randomly generates an
 * acceptable code from the [possiblePulseOximetryCodes] list, category is generated by base-vital-signs
 */
fun rcdmObservationPulseOximetry(tenant: String, block: ObservationGenerator.() -> Unit): Observation {
    return observation {
        block.invoke(this)
        meta of rcdmMeta(RoninProfile.OBSERVATION_PULSE_OXIMETRY, tenant) {}
        extension of generateExtension(extension.generate(), tenantSourceExtension)
        identifier of identifier.generate() + rcdmIdentifiers(tenant, identifier)
        category of listOf(codeableConcept { coding of vitalSignsCategory })
        code of generateCodeableConcept(code.generate(), possiblePulseOximetryCodes.random())
        subject of generateSubject(subject.generate(), subjectReferenceOptions)
        effective of generateEffectiveDateTime(effective.generate(), possibleDateTime)
        value of valueQuantity
        component of pulseOxComponent
    }
}

private val valueQuantity = DynamicValue(
    DynamicValueType.QUANTITY,
    Quantity(
        value = Decimal(99),
        unit = "%O2".asFHIR(),
        system = CodeSystem.UCUM.uri,
        code = Code("%")
    )
)
private val flowRateCoding = listOf(
    Coding(system = CodeSystem.LOINC.uri, code = Code("3151-8"))
)
private val concentrationCoding = listOf(
    Coding(system = CodeSystem.LOINC.uri, code = Code("3150-0"))
)
private val pulseOxComponent = listOf(
    ObservationComponent(
        code = CodeableConcept(
            coding = flowRateCoding,
            text = "Flow Rate".asFHIR()
        ),
        value = DynamicValue(
            DynamicValueType.QUANTITY,
            Quantity(
                value = Decimal(value = 110.0),
                unit = "L/min".asFHIR(),
                system = CodeSystem.UCUM.uri,
                code = Code("L/min")
            )
        )
    ),
    ObservationComponent(
        code = CodeableConcept(
            coding = concentrationCoding,
            text = "Concentration".asFHIR()
        ),
        value = DynamicValue(
            DynamicValueType.QUANTITY,
            Quantity(
                value = Decimal(value = 70.0),
                unit = "%".asFHIR(),
                system = CodeSystem.UCUM.uri,
                code = Code("%")
            )
        )
    )
)

val possiblePulseOximetryCodes = listOf(
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("89276-0")
        display of "Oxygen saturation in Arterial blood by Pulse oximetry --W exercise"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59413-5")
        display of "Oxygen saturation in Arterial blood by Pulse oximetry --post treatment"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59418-4")
        display of "Oxygen saturation in Blood Postductal by Pulse oximetry"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59409-3")
        display of "Oxygen saturation in Arterial blood by Pulse oximetry --during treatment"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59417-6")
        display of "Oxygen saturation in Arterial blood by Pulse oximetry --resting"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59406-9")
        display of "Oxygen saturation (8 hour minimum) in Arterial blood Pulse oximetry"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59414-3")
        display of "Oxygen saturation in Arterial blood by Pulse oximetry --pre bronchodilation"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59410-1")
        display of "Oxygen saturation in Arterial blood by Pulse oximetry --on room air"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("98148-0")
        display of "Oxygen saturation in 12 hour mean Arterial blood by Pulse oximetry"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("89277-8")
        display of "Oxygen saturation in Arterial blood by Pulse oximetry --during anesthesia"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59407-7")
        display of "Oxygen saturation in Blood Preductal by Pulse oximetry"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59412-7")
        display of "Oxygen saturation in Arterial blood by Pulse oximetry --post exercise"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59408-5")
        display of "Oxygen saturation in Arterial blood by Pulse oximetry"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59416-8")
        display of "Oxygen saturation in Arterial blood by Pulse oximetry --pre treatment"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59415-0")
        display of "Oxygen saturation in Arterial blood by Pulse oximetry --pre physiotherapy"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59405-1")
        display of "Oxygen saturation (8 hour maximum) in Arterial blood Pulse oximetry"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("59411-9")
        display of "Oxygen saturation in Arterial blood by Pulse oximetry --post bronchodilation"
    }
)
