package com.projectronin.interop.fhir.ronin.generators.resource.observation

import com.projectronin.interop.fhir.generators.datatypes.codeableConcept
import com.projectronin.interop.fhir.generators.datatypes.coding
import com.projectronin.interop.fhir.generators.primitives.of
import com.projectronin.interop.fhir.generators.resources.ObservationGenerator
import com.projectronin.interop.fhir.r4.datatype.primitive.Code
import com.projectronin.interop.fhir.r4.resource.Observation
import com.projectronin.interop.fhir.r4.resource.Patient
import com.projectronin.interop.fhir.ronin.generators.resource.referenceData
import com.projectronin.interop.fhir.ronin.generators.util.generateCodeableConcept
import com.projectronin.interop.fhir.ronin.generators.util.generateEffectiveDateTime
import com.projectronin.interop.fhir.ronin.generators.util.generateReference
import com.projectronin.interop.fhir.ronin.generators.util.rcdmMeta
import com.projectronin.interop.fhir.ronin.normalization.ValueSetList
import com.projectronin.interop.fhir.ronin.profile.RoninProfile
import com.projectronin.interop.fhir.ronin.validation.ValueSetMetadata

/**
 * Helps generate ronin body temperature observation profile, applies meta and randomly generates an
 * acceptable code from the [possibleBodyTemperatureCodes] list, category is generated by base-vital-signs
 */
fun rcdmObservationBodyTemperature(
    tenant: String,
    block: ObservationGenerator.() -> Unit,
): Observation {
    return rcdmBaseObservation(tenant) {
        block.invoke(this)
        meta of rcdmMeta(RoninProfile.OBSERVATION_BODY_TEMPERATURE, tenant) {}
        category of listOf(codeableConcept { coding of vitalSignsCategory })
        code of generateCodeableConcept(code.generate(), possibleBodyTemperatureCodes.codes.random())
        subject of generateReference(subject.generate(), subjectReferenceOptions, tenant, "Patient")
        effective of generateEffectiveDateTime(effective.generate(), possibleDateTime)
    }
}

fun Patient.rcdmObservationBodyTemperature(block: ObservationGenerator.() -> Unit): Observation {
    val data = this.referenceData()
    return rcdmObservationBodyTemperature(data.tenantId) {
        block.invoke(this)
        subject of
            generateReference(
                subject.generate(),
                subjectReferenceOptions,
                data.tenantId,
                "Patient",
                data.udpId,
            )
    }
}

val possibleBodyTemperatureCodes =
    ValueSetList(
        listOf(
            coding {
                system of "http://loinc.org"
                version of "2.74"
                code of Code("8310-5")
                display of "Body temperature"
            },
            coding {
                system of "http://loinc.org"
                version of "2.74"
                code of Code("8331-1")
                display of "Oral temperature"
            },
            coding {
                system of "http://loinc.org"
                version of "2.74"
                code of Code("76011-6")
                display of "Ear temperature"
            },
            coding {
                system of "http://loinc.org"
                version of "2.74"
                code of Code("11289-6")
                display of "Body temperature at First encounter"
            },
            coding {
                system of "http://loinc.org"
                version of "2.74"
                code of Code("8333-7")
                display of "Tympanic membrane temperature"
            },
            coding {
                system of "http://loinc.org"
                version of "2.74"
                code of Code("75539-7")
                display of "Body temperature - Temporal artery"
            },
        ),
        ValueSetMetadata(
            registryEntryType = "value_set",
            valueSetName = "bodytemperaturenoninvasive",
            valueSetUuid = "798f075e-a48d-49d2-8ace-66aff6f55478",
            version = "2",
        ),
    )
