package com.projectronin.interop.fhir.ronin.generators.resource.observation

import com.projectronin.interop.fhir.generators.datatypes.codeableConcept
import com.projectronin.interop.fhir.generators.datatypes.coding
import com.projectronin.interop.fhir.generators.resources.ObservationGenerator
import com.projectronin.interop.fhir.generators.resources.observation
import com.projectronin.interop.fhir.r4.datatype.primitive.Code
import com.projectronin.interop.fhir.r4.resource.Observation
import com.projectronin.interop.fhir.ronin.generators.util.generateCode
import com.projectronin.interop.fhir.ronin.generators.util.generateEffectiveDateTime
import com.projectronin.interop.fhir.ronin.generators.util.generateExtension
import com.projectronin.interop.fhir.ronin.generators.util.generateSubject
import com.projectronin.interop.fhir.ronin.generators.util.rcdmIdentifiers
import com.projectronin.interop.fhir.ronin.generators.util.rcdmMeta
import com.projectronin.interop.fhir.ronin.profile.RoninProfile

/**
 * Helps generate ronin body temperature observation profile, applies meta and randomly generates an
 * acceptable code from the [possibleBodyTemperatureCodes] list, category is generated by base-vital-signs
 */
fun rcdmObservationBodyTemperature(tenant: String, block: ObservationGenerator.() -> Unit): Observation {
    return observation {
        block.invoke(this)
        meta of rcdmMeta(RoninProfile.OBSERVATION_BODY_TEMPERATURE, tenant) {}
        extension of generateExtension(extension.generate(), tenantSourceExtension)
        identifier of identifier.generate() + rcdmIdentifiers(tenant, identifier)
        category of listOf(codeableConcept { coding of vitalSignsCategory })
        code of generateCode(code.generate(), possibleBodyTemperatureCodes.random())
        subject of generateSubject(subject.generate(), subjectReferenceOptions)
        effective of generateEffectiveDateTime(effective.generate(), possibleDateTime)
    }
}

val possibleBodyTemperatureCodes = listOf(
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("8310-5")
        display of "Body temperature"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("8331-1")
        display of "Oral temperature"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("76011-6")
        display of "Ear temperature"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("11289-6")
        display of "Body temperature at First encounter"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("8333-7")
        display of "Tympanic membrane temperature"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("75539-7")
        display of "Body temperature - Temporal artery"
    }
)
