package com.projectronin.interop.fhir.ronin.generators.resource.observation

import com.projectronin.interop.fhir.generators.datatypes.codeableConcept
import com.projectronin.interop.fhir.generators.datatypes.coding
import com.projectronin.interop.fhir.generators.resources.ObservationGenerator
import com.projectronin.interop.fhir.generators.resources.observation
import com.projectronin.interop.fhir.r4.datatype.primitive.Code
import com.projectronin.interop.fhir.r4.resource.Observation
import com.projectronin.interop.fhir.ronin.generators.util.generateCode
import com.projectronin.interop.fhir.ronin.generators.util.generateEffectiveDateTime
import com.projectronin.interop.fhir.ronin.generators.util.generateExtension
import com.projectronin.interop.fhir.ronin.generators.util.generateSubject
import com.projectronin.interop.fhir.ronin.generators.util.rcdmIdentifiers
import com.projectronin.interop.fhir.ronin.generators.util.rcdmMeta
import com.projectronin.interop.fhir.ronin.profile.RoninProfile

/**
 * Helps generate ronin heart rate observation profile, applies meta and randomly generates an
 * acceptable code from the [possibleHeartRateCodes] list, category is generated by base-vital-signs
 */
fun rcdmObservationHeartRate(tenant: String, block: ObservationGenerator.() -> Unit): Observation {
    return observation {
        block.invoke(this)
        meta of rcdmMeta(RoninProfile.OBSERVATION_HEART_RATE, tenant) {}
        extension of generateExtension(extension.generate(), tenantSourceExtension)
        identifier of identifier.generate() + rcdmIdentifiers(tenant, identifier)
        category of listOf(codeableConcept { coding of vitalSignsCategory })
        code of generateCode(code.generate(), possibleHeartRateCodes.random())
        subject of generateSubject(subject.generate(), subjectReferenceOptions)
        effective of generateEffectiveDateTime(effective.generate(), possibleDateTime)
    }
}

val possibleHeartRateCodes = listOf(
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("8867-4")
        display of "Heart rate"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("76477-9")
        display of "Heart rate by Noninvasive"
    },
    coding {
        system of "http://loinc.org"
        version of "2.74"
        code of Code("11328-2")
        display of "Heart rate at First encounter"
    }
)
