[libraries]
commons-text = "org.apache.commons:commons-text:1.10.0"
dd-trace-api = "com.datadoghq:dd-trace-api:1.6.0"

interop-aidbox = "com.projectronin.interop.publish:interop-aidbox:7.3.0"

interop-common = "com.projectronin.interop:interop-common:3.3.0"
interop-commonHttp = "com.projectronin.interop:interop-common-http:3.3.0"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:3.3.0"
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:3.3.0"

interop-datalake = "com.projectronin.interop.publish:interop-datalake:7.3.0"

interop-fhir = "com.projectronin.interop.fhir:interop-fhir:7.0.0"

interop-validation-client = "com.projectronin.interop.validation:interop-validation-client:1.1.0"

jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.14.2"
jackson-datatype-jsr310 = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.2"
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
ktor-server-auth-jwt = "io.ktor:ktor-server-auth-jwt:2.2.3"
ktorm-core = "org.ktorm:ktorm-core:3.6.0"
mockk = "io.mockk:mockk:1.13.4"
mockwebserver = "com.squareup.okhttp3:mockwebserver:4.10.0"
mysql-connector-java = "com.mysql:mysql-connector-j:8.0.32"
opentracing-api = "io.opentracing:opentracing-api:0.33.0"
opentracing-util = "io.opentracing:opentracing-util:0.33.0"
swagger-annotations = "io.swagger.core.v3:swagger-annotations:2.2.8"
testcontainers-mysql = "org.testcontainers:mysql:1.17.6"

[bundles]
test-mysql = ["mysql-connector-java", "testcontainers-mysql"]
