[libraries]
commons-text = "org.apache.commons:commons-text:1.9"
interop-common = "com.projectronin.interop:interop-common:1.0.0"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:1.0.0"
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:1.0.0"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:1.0.0"
mockwebserver = "com.squareup.okhttp3:mockwebserver:4.9.3"
