[libraries]
commons-text = "org.apache.commons:commons-text:1.9"
interop-aidbox = "com.projectronin.interop.publish:interop-aidbox:2.1.1"
interop-common = "com.projectronin.interop:interop-common:2.1.1"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:2.1.1"
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:2.1.1"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:1.2.2-refactor-SNAPSHOT"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.13.3"
jackson-datatype-jsr310 = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.3"
ktor-client-cio = "io.ktor:ktor-client-cio:2.0.3"
ktor-client-core = "io.ktor:ktor-client-core:2.0.3"
ktor-client-content-negotiation = "io.ktor:ktor-client-content-negotiation:2.0.3"
ktor-serialization-jackson = "io.ktor:ktor-serialization-jackson:2.0.3"
ktor-server-auth-jwt = "io.ktor:ktor-server-auth-jwt:2.0.3"
ktorm-core = "org.ktorm:ktorm-core:3.5.0"
mockk = "io.mockk:mockk:1.12.4"
mockwebserver = "com.squareup.okhttp3:mockwebserver:4.10.0"
mysql-connector-java = "mysql:mysql-connector-java:8.0.29"
rider-core = "com.github.database-rider:rider-core:1.32.3"
swagger-annotations = "io.swagger.core.v3:swagger-annotations:2.2.2"
testcontainers-mysql = "org.testcontainers:mysql:1.17.3"

[bundles]
test-mysql = ["mysql-connector-java", "testcontainers-mysql"]
