[libraries]
commons-text = "org.apache.commons:commons-text:1.9"
interop-common = "com.projectronin.interop:interop-common:2.0.0-SNAPSHOT"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:1.0.0"
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:1.0.0"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:1.0.0"
mockwebserver = "com.squareup.okhttp3:mockwebserver:4.9.3"
ktor-client-cio = "io.ktor:ktor-client-cio:2.0.1"
ktor-client-core = "io.ktor:ktor-client-core:2.0.1"
ktor-client-content-negotiation = "io.ktor:ktor-client-content-negotiation:2.0.1"
ktor-serialization-jackson = "io.ktor:ktor-serialization-jackson:2.0.1"
ktor-server-auth-jwt = "io.ktor:ktor-server-auth-jwt:2.0.1"
swagger-annotations = "io.swagger.core.v3:swagger-annotations:2.1.12"
