[libraries]
commons-text = "org.apache.commons:commons-text:1.10.0"
dd-trace-api = "com.datadoghq:dd-trace-api:1.1.3"
interop-aidbox = "com.projectronin.interop.publish:interop-aidbox:5.0.0"
interop-common = "com.projectronin.interop:interop-common:3.1.0"
interop-commonHttp = "com.projectronin.interop:interop-common-http:3.1.0"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:3.1.0"
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:3.1.0"
interop-datalake = "com.projectronin.interop.publish:interop-datalake:5.0.0"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:4.0.0"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.14.1"
jackson-datatype-jsr310 = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.0"
ktor-server-auth-jwt = "io.ktor:ktor-server-auth-jwt:2.1.3"
ktorm-core = "org.ktorm:ktorm-core:3.5.0"
mockk = "io.mockk:mockk:1.13.2"
mockwebserver = "com.squareup.okhttp3:mockwebserver:4.10.0"
mysql-connector-java = "com.mysql:mysql-connector-j:8.0.31"
swagger-annotations = "io.swagger.core.v3:swagger-annotations:2.2.7"
testcontainers-mysql = "org.testcontainers:mysql:1.17.6"

[bundles]
test-mysql = ["mysql-connector-java", "testcontainers-mysql"]
