databaseChangeLog:
  - changeSet:
      id: io-mirth-tenant-config-add-allowed-resources
      author: Z
      preConditions:
        - onFail: MARK_RAN
          not:
            - columnExists:
                tableName: io_mirth_tenant_config
                columnName: allowed_resources
      changes:
        - addColumn:
            tableName: io_mirth_tenant_config
            columns:
              - column:
                  name: allowed_resources
                  type: java.sql.Types.VARCHAR(2048)
                  constraints:
                    nullable: true
