name: (Retroactive Release) Build interop-ehr-liquibase image, push to Nexus, and sync with ArgoCD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        type: string
        required: true

jobs:
  get-info:
    name: Standard tags
    runs-on: self-hosted
    env:
      base_directory: ./interop-ehr-liquibase

    outputs:
      docker_image_tag: ${{ steps.gradle_info.outputs.docker_image_tag }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "zulu"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: "."

      - name: Get tag from Gradle
        id: gradle_info
        run: |
          TAG=$(./gradlew currentVersion | awk '{ if(/Project version:/) { print $3; exit } }' | cut -d\- -f1)
          echo ${TAG}
          echo "::set-output name=docker_image_tag::${TAG}"
        working-directory: "."

  image-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push multiplatform Docker to Nexus
    needs:
      - get-info
    uses: projectronin/github/.github/workflows/image_push_nexus.yml@master
    with:
      base-directory: ./interop-ehr-liquibase
      image-tag: ${{ needs.get-info.outputs.docker_image_tag }}
      repo: "interop-ehr-liquibase"
    secrets:
      username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}

  image-push-sha:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push multiplatform Docker to Nexus
    needs:
      - get-info
      - image-push
    uses: projectronin/github/.github/workflows/image_push_nexus.yml@master
    with:
      base-directory: ./interop-ehr-liquibase
      image-tag: ${{ github.sha }}
      repo: "interop-ehr-liquibase"
    secrets:
      username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}

  image-push-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push multiplatform Docker to Nexus
    needs:
      - get-info
      - image-push
    uses: projectronin/github/.github/workflows/image_push_nexus.yml@master
    with:
      base-directory: ./interop-ehr-liquibase
      image-tag: dev
      repo: "interop-ehr-liquibase"
    secrets:
      username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}
